spring.application.name=aplazo-fullstack-challenge

# Server
server.port=8080

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/challenge_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:challenge_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:challenge_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway (si lo estás usando)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# HikariCP settings (opcional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

# Server Security
server.tomcat.connection-timeout=5000

# Logging
logging.level.org.springframework=INFO
logging.level.com.aplazo=DEBUG

#Base path
server.servlet.context-path=/v1

# Custom
rate.limit.max-requests-per-minute=${RATE_LIMIT_MAX_REQUESTS_PER_MINUTE:10}
