package com.aplazo.challenge.aplazo_fullstack_challenge.mapper;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import com.aplazo.challenge.aplazo_fullstack_challenge.dto.customer.CustomerRequest;
import com.aplazo.challenge.aplazo_fullstack_challenge.dto.customer.CustomerResponse;
import com.aplazo.challenge.aplazo_fullstack_challenge.entity.CustomerEntity;

@ExtendWith(MockitoExtension.class)
@DisplayName("Customer Mapper Tests")
class CustomerMapperTest {

    private final CustomerMapper customerMapper = new CustomerMapperImpl(); // Generated by MapStruct

    @Test
    @DisplayName("Should map CustomerRequest to CustomerEntity correctly")
    void shouldMapCustomerRequestToCustomerEntityCorrectly() {
        // Given
        CustomerRequest request = new CustomerRequest();
        request.setFirstName("Juan");
        request.setLastName("Pérez");
        request.setSecondLastName("López");
        request.setDateOfBirth(LocalDate.of(1990, 5, 15));

        // When
        CustomerEntity entity = customerMapper.toEntity(request);

        // Then
        assertThat(entity).isNotNull();
        assertThat(entity.getFirstName()).isEqualTo("Juan");
        assertThat(entity.getLastName()).isEqualTo("Pérez");
        assertThat(entity.getSecondLastName()).isEqualTo("López");
        assertThat(entity.getDateOfBirth()).isEqualTo(LocalDate.of(1990, 5, 15));
        assertThat(entity.getId()).isNull(); // Should be null as it's not set by mapping
        assertThat(entity.getCreditLineAmount()).isNull(); // Should be null as it's not set by mapping
        assertThat(entity.getAvailableCreditLineAmount()).isNull(); // Should be null as it's not set by mapping
        assertThat(entity.getCreatedAt()).isNull(); // Should be null as it's not set by mapping
    }

    @Test
    @DisplayName("Should map CustomerEntity to CustomerResponse correctly")
    void shouldMapCustomerEntityToCustomerResponseCorrectly() {
        // Given
        UUID customerId = UUID.randomUUID();
        Instant createdAt = Instant.now();

        CustomerEntity entity = CustomerEntity.builder()
                .id(customerId)
                .firstName("María")
                .lastName("García")
                .secondLastName("Fernández")
                .dateOfBirth(LocalDate.of(1985, 8, 20))
                .creditLineAmount(new BigDecimal("1500.00"))
                .availableCreditLineAmount(new BigDecimal("1200.00"))
                .createdAt(createdAt)
                .build();

        // When
        CustomerResponse response = customerMapper.toResponse(entity);

        // Then
        assertThat(response).isNotNull();
        assertThat(response.getId()).isEqualTo(customerId);
        assertThat(response.getCreditLineAmount()).isEqualTo(new BigDecimal("1500.00"));
        assertThat(response.getAvailableCreditLineAmount()).isEqualTo(new BigDecimal("1200.00"));
        assertThat(response.getCreatedAt()).isEqualTo(createdAt);
    }

    @Test
    @DisplayName("Should handle null CustomerRequest")
    void shouldHandleNullCustomerRequest() {
        // When & Then
        CustomerEntity entity = customerMapper.toEntity(null);
        assertThat(entity).isNull();
    }

    @Test
    @DisplayName("Should handle null CustomerEntity")
    void shouldHandleNullCustomerEntity() {
        // When & Then
        CustomerResponse response = customerMapper.toResponse(null);
        assertThat(response).isNull();
    }

    @Test
    @DisplayName("Should map CustomerRequest with special characters correctly")
    void shouldMapCustomerRequestWithSpecialCharactersCorrectly() {
        // Given
        CustomerRequest request = new CustomerRequest();
        request.setFirstName("José María");
        request.setLastName("García-Rodríguez");
        request.setSecondLastName("Fernández-Muñoz");
        request.setDateOfBirth(LocalDate.of(1992, 12, 25));

        // When
        CustomerEntity entity = customerMapper.toEntity(request);

        // Then
        assertThat(entity.getFirstName()).isEqualTo("José María");
        assertThat(entity.getLastName()).isEqualTo("García-Rodríguez");
        assertThat(entity.getSecondLastName()).isEqualTo("Fernández-Muñoz");
        assertThat(entity.getDateOfBirth()).isEqualTo(LocalDate.of(1992, 12, 25));
    }

    @Test
    @DisplayName("Should preserve date precision when mapping")
    void shouldPreserveDatePrecisionWhenMapping() {
        // Given
        LocalDate specificDate = LocalDate.of(2000, 2, 29); // Leap year date
        CustomerRequest request = new CustomerRequest();
        request.setFirstName("Test");
        request.setLastName("User");
        request.setSecondLastName("Leap");
        request.setDateOfBirth(specificDate);

        // When
        CustomerEntity entity = customerMapper.toEntity(request);

        // Then
        assertThat(entity.getDateOfBirth()).isEqualTo(specificDate);
    }

    @Test
    @DisplayName("Should preserve BigDecimal precision when mapping entity to response")
    void shouldPreserveBigDecimalPrecisionWhenMappingEntityToResponse() {
        // Given
        BigDecimal preciseCreditLine = new BigDecimal("1234.5678");
        BigDecimal preciseAvailableCredit = new BigDecimal("999.1234");
        UUID customerId = UUID.randomUUID();

        CustomerEntity entity = CustomerEntity.builder()
                .id(customerId)
                .firstName("Precision")
                .lastName("Test")
                .secondLastName("User")
                .dateOfBirth(LocalDate.of(1990, 1, 1))
                .creditLineAmount(preciseCreditLine)
                .availableCreditLineAmount(preciseAvailableCredit)
                .createdAt(Instant.now())
                .build();

        // When
        CustomerResponse response = customerMapper.toResponse(entity);

        // Then
        assertThat(response.getCreditLineAmount().compareTo(preciseCreditLine)).isEqualTo(0);
        assertThat(response.getAvailableCreditLineAmount().compareTo(preciseAvailableCredit)).isEqualTo(0);
    }

    @Test
    @DisplayName("Should handle minimum and maximum dates correctly")
    void shouldHandleMinimumAndMaximumDatesCorrectly() {
        // Given - Test with edge case dates
        LocalDate oldDate = LocalDate.of(1900, 1, 1);
        LocalDate futureDate = LocalDate.of(2100, 12, 31);

        CustomerRequest oldRequest = new CustomerRequest();
        oldRequest.setFirstName("Very");
        oldRequest.setLastName("Old");
        oldRequest.setSecondLastName("Customer");
        oldRequest.setDateOfBirth(oldDate);

        CustomerRequest futureRequest = new CustomerRequest();
        futureRequest.setFirstName("Future");
        futureRequest.setLastName("Born");
        futureRequest.setSecondLastName("Customer");
        futureRequest.setDateOfBirth(futureDate);

        // When
        CustomerEntity oldEntity = customerMapper.toEntity(oldRequest);
        CustomerEntity futureEntity = customerMapper.toEntity(futureRequest);

        // Then
        assertThat(oldEntity.getDateOfBirth()).isEqualTo(oldDate);
        assertThat(futureEntity.getDateOfBirth()).isEqualTo(futureDate);
    }

    @Test
    @DisplayName("Should handle long names without truncation")
    void shouldHandleLongNamesWithoutTruncation() {
        // Given
        String longName = "A".repeat(255); // Very long name
        CustomerRequest request = new CustomerRequest();
        request.setFirstName(longName);
        request.setLastName(longName);
        request.setSecondLastName(longName);
        request.setDateOfBirth(LocalDate.of(1990, 1, 1));

        // When
        CustomerEntity entity = customerMapper.toEntity(request);

        // Then
        assertThat(entity.getFirstName()).isEqualTo(longName);
        assertThat(entity.getLastName()).isEqualTo(longName);
        assertThat(entity.getSecondLastName()).isEqualTo(longName);
    }

    @Test
    @DisplayName("Should map response with UUIDv7 correctly")
    void shouldMapResponseWithUuidV7Correctly() {
        // Given - Create a UUIDv7 (this would normally be generated by the application)
        UUID uuidV7 = UUID.randomUUID(); // In real code, this would be generated as UUIDv7
        Instant createdAt = Instant.now();

        CustomerEntity entity = CustomerEntity.builder()
                .id(uuidV7)
                .firstName("UUID")
                .lastName("Test")
                .secondLastName("Customer")
                .dateOfBirth(LocalDate.of(1990, 1, 1))
                .creditLineAmount(new BigDecimal("1000.00"))
                .availableCreditLineAmount(new BigDecimal("800.00"))
                .createdAt(createdAt)
                .build();

        // When
        CustomerResponse response = customerMapper.toResponse(entity);

        // Then
        assertThat(response.getId()).isEqualTo(uuidV7);
        assertThat(response.getCreatedAt()).isEqualTo(createdAt);
    }

    @Test
    @DisplayName("Should handle zero and negative amounts in response mapping")
    void shouldHandleZeroAndNegativeAmountsInResponseMapping() {
        // Given
        UUID customerId = UUID.randomUUID();
        CustomerEntity entity = CustomerEntity.builder()
                .id(customerId)
                .firstName("Zero")
                .lastName("Balance")
                .secondLastName("Customer")
                .dateOfBirth(LocalDate.of(1990, 1, 1))
                .creditLineAmount(BigDecimal.ZERO)
                .availableCreditLineAmount(new BigDecimal("-50.00")) // Negative available credit
                .createdAt(Instant.now())
                .build();

        // When
        CustomerResponse response = customerMapper.toResponse(entity);

        // Then
        assertThat(response.getCreditLineAmount()).isEqualTo(BigDecimal.ZERO);
        assertThat(response.getAvailableCreditLineAmount()).isEqualTo(new BigDecimal("-50.00"));
    }
}
