package com.aplazo.challenge.aplazo_fullstack_challenge.mapper;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import com.aplazo.challenge.aplazo_fullstack_challenge.dto.loan.LoanRequest;
import com.aplazo.challenge.aplazo_fullstack_challenge.dto.loan.LoanResponse;
import com.aplazo.challenge.aplazo_fullstack_challenge.entity.CustomerEntity;
import com.aplazo.challenge.aplazo_fullstack_challenge.entity.InstallmentEntity;
import com.aplazo.challenge.aplazo_fullstack_challenge.entity.LoanEntity;
import com.aplazo.challenge.aplazo_fullstack_challenge.enums.InstallmentStatus;
import com.aplazo.challenge.aplazo_fullstack_challenge.enums.LoanStatus;

@ExtendWith(MockitoExtension.class)
@DisplayName("Loan Mapper Tests")
class LoanMapperTest {

    private final LoanMapper loanMapper = new LoanMapperImpl(); // Generated by MapStruct

    @Test
    @DisplayName("Should map LoanRequest to LoanEntity correctly")
    void shouldMapLoanRequestToLoanEntityCorrectly() {
        // Given
        UUID customerId = UUID.randomUUID();
        LoanRequest request = new LoanRequest();
        request.setCustomerId(customerId);
        request.setAmount(new BigDecimal("1000.00"));

        // When
        LoanEntity entity = loanMapper.toEntity(request);

        // Then
        assertThat(entity).isNotNull();
        assertThat(entity.getAmount()).isEqualTo(new BigDecimal("1000.00"));
        assertThat(entity.getId()).isNull(); // Should be null as it's not set by mapping
        assertThat(entity.getCustomer()).isNull(); // Should be null as it's not set by mapping
        assertThat(entity.getStatus()).isNull(); // Should be null as it's not set by mapping
        assertThat(entity.getCommissionAmount()).isNull(); // Should be null as it's not set by mapping
        assertThat(entity.getCreatedAt()).isNull(); // Should be null as it's not set by mapping
    }

    @Test
    @DisplayName("Should map LoanEntity to LoanResponse correctly")
    void shouldMapLoanEntityToLoanResponseCorrectly() {
        // Given
        UUID loanId = UUID.randomUUID();
        UUID customerId = UUID.randomUUID();
        LocalDateTime createdAt = LocalDateTime.now();

        CustomerEntity customer = CustomerEntity.builder()
                .id(customerId)
                .firstName("Test")
                .lastName("Customer")
                .secondLastName("User")
                .dateOfBirth(LocalDate.of(1990, 1, 1))
                .creditLineAmount(new BigDecimal("1000.00"))
                .availableCreditLineAmount(new BigDecimal("500.00"))
                .createdAt(Instant.now())
                .build();

        List<InstallmentEntity> installments = createTestInstallments(loanId);

        LoanEntity entity = LoanEntity.builder()
                .id(loanId)
                .customer(customer)
                .amount(new BigDecimal("500.00"))
                .status(LoanStatus.ACTIVE)
                .commissionAmount(new BigDecimal("25.00"))
                .createdAt(createdAt)
                .installments(installments)
                .build();

        // When
        LoanResponse response = loanMapper.toResponse(entity);

        // Then
        assertThat(response).isNotNull();
        assertThat(response.getId()).isEqualTo(loanId);
        assertThat(response.getCustomerId()).isEqualTo(customerId);
        assertThat(response.getAmount()).isEqualTo(new BigDecimal("500.00"));
        assertThat(response.getStatus()).isEqualTo(LoanStatus.ACTIVE);
        assertThat(response.getCreatedAt()).isEqualTo(createdAt);

        // Verify payment plan
        assertThat(response.getPaymentPlan()).isNotNull();
        assertThat(response.getPaymentPlan().getCommissionAmount()).isEqualTo(new BigDecimal("25.00"));
        assertThat(response.getPaymentPlan().getInstallments()).hasSize(5);

        // Verify first installment
        assertThat(response.getPaymentPlan().getInstallments().get(0).getStatus()).isEqualTo(InstallmentStatus.NEXT);
        assertThat(response.getPaymentPlan().getInstallments().get(0).getAmount()).isEqualTo(new BigDecimal("105.00"));

        // Verify remaining installments
        for (int i = 1; i < 5; i++) {
            assertThat(response.getPaymentPlan().getInstallments().get(i).getStatus())
                    .isEqualTo(InstallmentStatus.PENDING);
            assertThat(response.getPaymentPlan().getInstallments().get(i).getAmount())
                    .isEqualTo(new BigDecimal("105.00"));
        }
    }

    @Test
    @DisplayName("Should handle null LoanRequest")
    void shouldHandleNullLoanRequest() {
        // When & Then
        LoanEntity entity = loanMapper.toEntity(null);
        assertThat(entity).isNull();
    }

    @Test
    @DisplayName("Should handle null LoanEntity")
    void shouldHandleNullLoanEntity() {
        // When & Then
        LoanResponse response = loanMapper.toResponse(null);
        assertThat(response).isNull();
    }

    @Test
    @DisplayName("Should map LoanRequest with very small amount correctly")
    void shouldMapLoanRequestWithVerySmallAmountCorrectly() {
        // Given
        UUID customerId = UUID.randomUUID();
        LoanRequest request = new LoanRequest();
        request.setCustomerId(customerId);
        request.setAmount(new BigDecimal("0.01"));

        // When
        LoanEntity entity = loanMapper.toEntity(request);

        // Then
        assertThat(entity.getAmount()).isEqualTo(new BigDecimal("0.01"));
    }

    @Test
    @DisplayName("Should map LoanRequest with very large amount correctly")
    void shouldMapLoanRequestWithVeryLargeAmountCorrectly() {
        // Given
        UUID customerId = UUID.randomUUID();
        LoanRequest request = new LoanRequest();
        request.setCustomerId(customerId);
        request.setAmount(new BigDecimal("999999.99"));

        // When
        LoanEntity entity = loanMapper.toEntity(request);

        // Then
        assertThat(entity.getAmount()).isEqualTo(new BigDecimal("999999.99"));
    }

    @Test
    @DisplayName("Should preserve BigDecimal precision when mapping")
    void shouldPreserveBigDecimalPrecisionWhenMapping() {
        // Given
        UUID customerId = UUID.randomUUID();
        BigDecimal preciseAmount = new BigDecimal("123.456789");
        LoanRequest request = new LoanRequest();
        request.setCustomerId(customerId);
        request.setAmount(preciseAmount);

        // When
        LoanEntity entity = loanMapper.toEntity(request);

        // Then
        assertThat(entity.getAmount().compareTo(preciseAmount)).isEqualTo(0);
    }

    @Test
    @DisplayName("Should map LoanEntity with different loan statuses correctly")
    void shouldMapLoanEntityWithDifferentLoanStatusesCorrectly() {
        // Given
        UUID loanId = UUID.randomUUID();
        UUID customerId = UUID.randomUUID();

        CustomerEntity customer = createTestCustomer(customerId);
        List<InstallmentEntity> installments = createTestInstallments(loanId);

        // Test each loan status
        LoanStatus[] statuses = { LoanStatus.ACTIVE, LoanStatus.LATE, LoanStatus.COMPLETED };

        for (LoanStatus status : statuses) {
            LoanEntity entity = LoanEntity.builder()
                    .id(loanId)
                    .customer(customer)
                    .amount(new BigDecimal("1000.00"))
                    .status(status)
                    .commissionAmount(new BigDecimal("50.00"))
                    .createdAt(LocalDateTime.now())
                    .installments(installments)
                    .build();

            // When
            LoanResponse response = loanMapper.toResponse(entity);

            // Then
            assertThat(response.getStatus()).isEqualTo(status);
        }
    }

    @Test
    @DisplayName("Should map LoanEntity with empty installments list")
    void shouldMapLoanEntityWithEmptyInstallmentsList() {
        // Given
        UUID loanId = UUID.randomUUID();
        UUID customerId = UUID.randomUUID();

        CustomerEntity customer = createTestCustomer(customerId);

        LoanEntity entity = LoanEntity.builder()
                .id(loanId)
                .customer(customer)
                .amount(new BigDecimal("1000.00"))
                .status(LoanStatus.ACTIVE)
                .commissionAmount(new BigDecimal("50.00"))
                .createdAt(LocalDateTime.now())
                .installments(new ArrayList<>()) // Empty list
                .build();

        // When
        LoanResponse response = loanMapper.toResponse(entity);

        // Then
        assertThat(response).isNotNull();
        assertThat(response.getPaymentPlan()).isNotNull();
        assertThat(response.getPaymentPlan().getInstallments()).isEmpty();
        assertThat(response.getPaymentPlan().getCommissionAmount()).isEqualTo(new BigDecimal("50.00"));
    }

    @Test
    @DisplayName("Should map LoanEntity with null installments list")
    void shouldMapLoanEntityWithNullInstallmentsList() {
        // Given
        UUID loanId = UUID.randomUUID();
        UUID customerId = UUID.randomUUID();

        CustomerEntity customer = createTestCustomer(customerId);

        LoanEntity entity = LoanEntity.builder()
                .id(loanId)
                .customer(customer)
                .amount(new BigDecimal("1000.00"))
                .status(LoanStatus.ACTIVE)
                .commissionAmount(new BigDecimal("50.00"))
                .createdAt(LocalDateTime.now())
                .installments(null) // Null list
                .build();

        // When
        LoanResponse response = loanMapper.toResponse(entity);

        // Then
        assertThat(response).isNotNull();
        assertThat(response.getPaymentPlan()).isNotNull();
        assertThat(response.getPaymentPlan().getInstallments()).isNull();
        assertThat(response.getPaymentPlan().getCommissionAmount()).isEqualTo(new BigDecimal("50.00"));
    }

    @Test
    @DisplayName("Should map installment scheduled payment dates correctly")
    void shouldMapInstallmentScheduledPaymentDatesCorrectly() {
        // Given
        UUID loanId = UUID.randomUUID();
        UUID customerId = UUID.randomUUID();

        CustomerEntity customer = createTestCustomer(customerId);

        LocalDate today = LocalDate.now();
        List<InstallmentEntity> installments = new ArrayList<>();

        // Create a loan entity for the installments to reference
        LoanEntity loanEntity = LoanEntity.builder()
                .id(loanId)
                .amount(new BigDecimal("500.00"))
                .status(LoanStatus.ACTIVE)
                .commissionAmount(new BigDecimal("25.00"))
                .createdAt(LocalDateTime.now())
                .build();

        for (int i = 0; i < 5; i++) {
            InstallmentEntity installment = InstallmentEntity.builder()
                    .id(UUID.randomUUID())
                    .loan(loanEntity) // Set the loan relationship
                    .amount(new BigDecimal("105.00"))
                    .scheduledPaymentDate(today.plusWeeks(2L * (i + 1)))
                    .status(i == 0 ? InstallmentStatus.NEXT : InstallmentStatus.PENDING)
                    .build();
            installments.add(installment);
        }

        LoanEntity entity = LoanEntity.builder()
                .id(loanId)
                .customer(customer)
                .amount(new BigDecimal("500.00"))
                .status(LoanStatus.ACTIVE)
                .commissionAmount(new BigDecimal("25.00"))
                .createdAt(LocalDateTime.now())
                .installments(installments)
                .build();

        // When
        LoanResponse response = loanMapper.toResponse(entity);

        // Then
        assertThat(response.getPaymentPlan().getInstallments()).hasSize(5);

        for (int i = 0; i < 5; i++) {
            LocalDate expectedDate = today.plusWeeks(2L * (i + 1));
            assertThat(response.getPaymentPlan().getInstallments().get(i).getScheduledPaymentDate())
                    .isEqualTo(expectedDate);
        }
    }

    @Test
    @DisplayName("Should map installments with different statuses correctly")
    void shouldMapInstallmentsWithDifferentStatusesCorrectly() {
        // Given
        UUID loanId = UUID.randomUUID();
        UUID customerId = UUID.randomUUID();

        CustomerEntity customer = createTestCustomer(customerId);

        List<InstallmentEntity> installments = new ArrayList<>();
        InstallmentStatus[] statuses = {
                InstallmentStatus.NEXT,
                InstallmentStatus.PENDING,
                InstallmentStatus.PENDING,
                InstallmentStatus.PENDING,
                InstallmentStatus.ERROR
        };

        // Create a loan entity for the installments to reference
        LoanEntity loanEntity = LoanEntity.builder()
                .id(loanId)
                .amount(new BigDecimal("500.00"))
                .status(LoanStatus.LATE)
                .commissionAmount(new BigDecimal("25.00"))
                .createdAt(LocalDateTime.now())
                .build();

        for (int i = 0; i < 5; i++) {
            InstallmentEntity installment = InstallmentEntity.builder()
                    .id(UUID.randomUUID())
                    .loan(loanEntity) // Set the loan relationship
                    .amount(new BigDecimal("105.00"))
                    .scheduledPaymentDate(LocalDate.now().plusWeeks(2L * (i + 1)))
                    .status(statuses[i])
                    .build();
            installments.add(installment);
        }

        LoanEntity entity = LoanEntity.builder()
                .id(loanId)
                .customer(customer)
                .amount(new BigDecimal("500.00"))
                .status(LoanStatus.LATE)
                .commissionAmount(new BigDecimal("25.00"))
                .createdAt(LocalDateTime.now())
                .installments(installments)
                .build();

        // When
        LoanResponse response = loanMapper.toResponse(entity);

        // Then
        for (int i = 0; i < 5; i++) {
            assertThat(response.getPaymentPlan().getInstallments().get(i).getStatus())
                    .isEqualTo(statuses[i]);
        }
    }

    @Test
    @DisplayName("Should handle zero commission amount correctly")
    void shouldHandleZeroCommissionAmountCorrectly() {
        // Given
        UUID loanId = UUID.randomUUID();
        UUID customerId = UUID.randomUUID();

        CustomerEntity customer = createTestCustomer(customerId);
        List<InstallmentEntity> installments = createTestInstallments(loanId);

        LoanEntity entity = LoanEntity.builder()
                .id(loanId)
                .customer(customer)
                .amount(new BigDecimal("1000.00"))
                .status(LoanStatus.ACTIVE)
                .commissionAmount(BigDecimal.ZERO)
                .createdAt(LocalDateTime.now())
                .installments(installments)
                .build();

        // When
        LoanResponse response = loanMapper.toResponse(entity);

        // Then
        assertThat(response.getPaymentPlan().getCommissionAmount()).isEqualTo(BigDecimal.ZERO);
    }

    private CustomerEntity createTestCustomer(UUID customerId) {
        return CustomerEntity.builder()
                .id(customerId)
                .firstName("Test")
                .lastName("Customer")
                .secondLastName("User")
                .dateOfBirth(LocalDate.of(1990, 1, 1))
                .creditLineAmount(new BigDecimal("1000.00"))
                .availableCreditLineAmount(new BigDecimal("500.00"))
                .createdAt(Instant.now())
                .build();
    }

    private List<InstallmentEntity> createTestInstallments(UUID loanId) {
        List<InstallmentEntity> installments = new ArrayList<>();
        LocalDate today = LocalDate.now();

        // Create a loan entity for the installments to reference
        LoanEntity loanEntity = LoanEntity.builder()
                .id(loanId)
                .amount(new BigDecimal("500.00"))
                .status(LoanStatus.ACTIVE)
                .commissionAmount(new BigDecimal("25.00"))
                .createdAt(LocalDateTime.now())
                .build();

        for (int i = 0; i < 5; i++) {
            InstallmentEntity installment = InstallmentEntity.builder()
                    .id(UUID.randomUUID())
                    .loan(loanEntity) // Set the loan relationship
                    .amount(new BigDecimal("105.00")) // 525 total / 5 installments
                    .scheduledPaymentDate(today.plusWeeks(2L * (i + 1)))
                    .status(i == 0 ? InstallmentStatus.NEXT : InstallmentStatus.PENDING)
                    .build();
            installments.add(installment);
        }

        return installments;
    }
}
